- name: Configure frontend (Red Hat Linux)
  hosts: frontend
  become: true
  vars:
    nginx_backend_ip: "3.92.196.48"
  tasks:
    - name: Disable SELinux temporarily
      command: setenforce 0
      when: ansible_selinux.status == "enabled"
      ignore_errors: yes

    - name: Permanently disable SELinux
      replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=.*'
        replace: 'SELINUX=disabled'

    - name: Disable firewalld
      dnf:
        name: firewalld
        state: absent
      ignore_errors: yes
   
    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Configure Nginx as reverse proxy
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user nginx;
          worker_processes auto;
          pid /run/nginx.pid;

          events {
            worker_connections 1024;
          }

          http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;
            access_log    /var/log/nginx/access.log;
            error_log     /var/log/nginx/error.log;

            sendfile        on;
            tcp_nopush      on;
            tcp_nodelay     on;
            keepalive_timeout 65;
            types_hash_max_size 2048;

            include /etc/nginx/conf.d/*.conf;

            server {
                listen 80;
                server_name localhost;

                location / {
                    proxy_pass http://{{ nginx_backend_ip }}:19999;
                    proxy_set_header Host $host;
                    proxy_set_header X-Real-IP $remote_addr;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                }
            }
          }

    - name: Ensure Nginx is running and enabled
      service:
        name: nginx
        state: started
        enabled: yes
