- name: Configure frontend (Amazon Linux 2)
  hosts: frontend
  become: true
  vars:
    nginx_backend_ip: "54.162.98.239"  # Replace with your backend IP

  tasks:
    - name: Install required packages for Python build
      yum:
        name:
          - gcc
          - openssl-devel
          - bzip2-devel
          - libffi-devel
          - wget
          - make
          - zlib-devel
          - tar
        state: present

    - name: Download Python 3.12.3 source
      get_url:
        url: https://www.python.org/ftp/python/3.12.3/Python-3.12.3.tgz
        dest: /usr/src/Python-3.12.3.tgz

    - name: Extract Python 3.12.3 source
      unarchive:
        src: /usr/src/Python-3.12.3.tgz
        dest: /usr/src/
        remote_src: yes

    - name: Compile and install Python 3.12.3
      shell: |
        cd /usr/src/Python-3.12.3
        ./configure --enable-optimizations
        make -j "$(nproc)"
        make altinstall
      args:
        creates: /usr/local/bin/python3.12

    - name: Set Python 3.12 as default python3
      alternatives:
        name: python3
        path: /usr/local/bin/python3.12
        priority: 1

    - name: Disable SELinux
      command: echo "SELinux not applicable on Amazon Linux"
      changed_when: false
      ignore_errors: true

    - name: Disable firewalld
      yum:
        name: firewalld
        state: absent

    - name: Enable nginx1 from Amazon Linux Extras
      command: amazon-linux-extras enable nginx1
      register: result
      changed_when: "'nginx1' in result.stdout"

    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Configure Nginx as reverse proxy
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user nginx;
          worker_processes auto;
